### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by sonnyp** [JCWasmx86/GTKCssLanguageServer#12]
I want to lint CSS files in Workbench CI.

Specially the demos CSS so we don't accept contributions that would produce GTKCssLanguageServer errors in Workbench

WDYT?

**Comment by JCWasmx86** [comment]
Made a really small/quick+dirty implementation:
- Prints the errors/warnings
- Just one file can be passed at once
- Exit code is either 1 or 0

Will make the parsing a bit more robust, if the need arises
